-- Camera/placement fields on stream (stream = camera).
ALTER TABLE streams
  ADD COLUMN IF NOT EXISTS position_x   DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS position_y   DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rotation     DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50);
